package project.d.pacman;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Ruben
 */
public class Hoofdscherm extends javax.swing.JFrame {

    /**
     * Creates new form Hoofdscherm
     */
    public Hoofdscherm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void mainframeInit(){
        JPanel basic = new JPanel();
        basic.setLayout(new BoxLayout(basic, BoxLayout.Y_AXIS));
        JFrame frame = new JFrame();
        frame.setLayout(new FlowLayout());
        
        Main main = new Main();
        
       
        JButton btReset = new JButton("Reset");
        btReset.addActionListener(new ActionListener() 
        { 
            @Override
            public void actionPerformed(ActionEvent e)
            {
                frame.dispose();
                mainframeInit();
            }
        });    
       
        JButton btPauze = new JButton("Pauze");
        btPauze.setFocusable(false);
        btPauze.addActionListener(new ActionListener() 
        { 
            @Override
            public void actionPerformed(ActionEvent e)
            {
                main.switchPause();
            }
        });
        
        JButton btExit = new JButton("   Exit  ");
        btExit.addActionListener(new ActionListener() 
        { 
            @Override
            public void actionPerformed(ActionEvent e)
            {
                frame.dispose();
                new Hoofdscherm().setVisible(true);
            }
        });     

        
        
        basic.add(btPauze);
        basic.add(btReset);
        basic.add(btExit);
        
        frame.add(basic);
        
        frame.add(main);
        
        frame.setResizable(false);

        frame.pack();


        //plaats in het midden van het scherm
        frame.setLocationRelativeTo(null);

        //stop met runnen bij sluiten scherm
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        main.init();
        

        //zorg dat de focus verkregen kan worden
        main.setFocusable(true);
        main.requestFocusInWindow();

        frame.setVisible(true);
        
        this.dispose();
    }
    
    private void instructionsInit(){
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        JFrame instrucframe = new JFrame();
        instrucframe.setLayout(new FlowLayout());
        
        InstructionsPanel instruc = new InstructionsPanel();
        
        JButton btExit = new JButton("Exit");
        btExit.addActionListener(new ActionListener() 
        { 
            @Override
            public void actionPerformed(ActionEvent e)
            {
                instrucframe.dispose();
                new Hoofdscherm().setVisible(true);
            }
        });
        
        panel.add(btExit);
        
        instrucframe.add(panel);
        
        instrucframe.add(instruc);
        
        instrucframe.setResizable(false);

        instrucframe.pack();
        
        instrucframe.setLocationRelativeTo(null);
        
        instrucframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        instruc.init();
        
        instruc.setFocusable(true);
        instruc.requestFocusInWindow();

        instrucframe.setVisible(true);
        
        this.dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btInstruc = new javax.swing.JButton();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btStart.setText("Start");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("Pac-Man");

        btInstruc.setText("Instructions");
        btInstruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInstrucActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btInstruc, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btStart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btInstruc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        mainframeInit();
    }//GEN-LAST:event_btStartActionPerformed

    private void btInstrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInstrucActionPerformed
        instructionsInit();
    }//GEN-LAST:event_btInstrucActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoofdscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoofdscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoofdscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoofdscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoofdscherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btInstruc;
    private javax.swing.JButton btStart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
